# Generated by Django 4.1.7 on 2023-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_maker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
