# Generated by Django 4.1.7 on 2023-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu_maker", "0003_alter_menuitem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
